/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CryptocurrencyApp;


import CryptocurrencyApp.Controller.Facade;
import CryptocurrencyApp.Controller.ListData;
import CryptocurrencyApp.Controller.Report;
import CryptocurrencyApp.GUI.MerchantFeePage;
import CryptocurrencyApp.Model.Database;
import CryptocurrencyApp.Model.RequestMaker;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        if (args.length < 2) {
            System.out.println("Not enough arguments");
            return;
        }
        if (args[0].equals("offline") && args[1].equals("offline")) {
            //gradle run --args="offline offline"
            ListData offlineData = new ListData(new Database());
            Report offlineReport = new Report();
            Facade facade = new Facade(offlineData, offlineReport);
            new MerchantFeePage(facade);
        } else if (args[0].equals("online") && args[1].equals("offline")) {
            //gradle run --args="online offline"
            try {
                File f = new File("ConfigKeys.txt");
                Scanner reader = new Scanner(f);
                String cmcKey = reader.nextLine();
                String pastebinKey = reader.nextLine();
                reader.close();

                ListData onlineData = new ListData(cmcKey, new RequestMaker(), new Database());
                Report offlineReport = new Report();
                Facade facade = new Facade(onlineData, offlineReport);
                new MerchantFeePage(facade);
            } catch (FileNotFoundException e) {
                System.out.println("An error occurred while accessing the file.");
                e.printStackTrace();
            }

        } else if (args[0].equals("offline") && args[1].equals("online")) {
            //gradle run --args="offline online"
            try {
                File f = new File("ConfigKeys.txt");
                Scanner reader = new Scanner(f);
                String cmcKey = reader.nextLine();
                String pastebinKey = reader.nextLine();
                reader.close();

                ListData offlineData = new ListData(new Database());
                Report onlineReport = new Report(pastebinKey, new RequestMaker());
                Facade facade = new Facade(offlineData, onlineReport);
                new MerchantFeePage(facade);
            } catch (FileNotFoundException e) {
                System.out.println("An error occurred while accessing the file.");
                e.printStackTrace();
            }

        } else if (args[0].equals("online") && args[1].equals("online")) {
            //gradle run --args="online online"
            try {
                File f = new File("ConfigKeys.txt");
                Scanner reader = new Scanner(f);
                String cmcKey = reader.nextLine();
                String pastebinKey = reader.nextLine();
                reader.close();

                ListData onlineData = new ListData(cmcKey, new RequestMaker(), new Database());
                Report onlineReport = new Report(pastebinKey, new RequestMaker());
                Facade facade = new Facade(onlineData, onlineReport);
                new MerchantFeePage(facade);
            } catch (FileNotFoundException e) {
                System.out.println("An error occurred while accessing the file.");
                e.printStackTrace();
            }

        }
    }
}
